In [1]:
import numpy as np  # Juan: importamos numpy para vectores y matrices

rng = np.random.default_rng()  # Juan: creamos un generador de numeros aleatorios reproducible si se fija la semilla

def leer_entero(mensaje):  # Juan: funcion para leer un entero del usuario con validacion

    while True:  # Juan: repetimos hasta que el usuario ingrese un entero valido

        try:  # Juan: intentamos convertir la entrada a entero

            return int(input(mensaje))  # Juan: devolvemos el valor entero ingresado

        except ValueError:  # Juan: si falla la conversion mostramos un aviso

            print("ingresa un numero entero valido")  # Juan: solicitamos un nuevo intento

def vector_aleatorio(n, bajo=-9, alto=10):  # Juan: genera un vector de enteros aleatorios de longitud n

    return rng.integers(bajo, alto, size=n)  # Juan: devolvemos un vector con valores entre bajo y alto

def matriz_aleatoria(filas, cols, bajo=-9, alto=10):  # Juan: genera una matriz de enteros aleatorios

    return rng.integers(bajo, alto, size=(filas, cols))  # Juan: devolvemos una matriz de dimensiones filas por cols


In [2]:
n = leer_entero("ingresa la longitud n del vector: ")  # Juan: pedimos la longitud de los vectores

v1 = vector_aleatorio(n)  # Juan: generamos el primer vector aleatorio

v2 = vector_aleatorio(n)  # Juan: generamos el segundo vector aleatorio

producto_escalar = int(np.dot(v1, v2))  # Juan: calculamos el producto escalar y lo convertimos a int para mostrar

print("vector 1:", v1)  # Juan: mostramos el primer vector

print("vector 2:", v2)  # Juan: mostramos el segundo vector

print("producto escalar:", producto_escalar)  # Juan: mostramos el resultado del producto escalar


ingresa la longitud n del vector: 4
vector 1: [-4 -3 -8  3]
vector 2: [-4 -8  2 -7]
producto escalar: 3


In [3]:
print("elige una operacion matricial")  # Juan: mostramos el menu de opciones

print("1 suma")  # Juan: opcion 1 suma de matrices

print("2 multiplicacion")  # Juan: opcion 2 multiplicacion de matrices

op = leer_entero("escribe 1 o 2 y presiona enter: ")  # Juan: leemos la opcion del usuario

if op == 1:  # Juan: si el usuario eligio suma

    m = rng.integers(2, 9)  # Juan: numero de filas entre 2 y 8

    n = rng.integers(2, 9)  # Juan: numero de columnas entre 2 y 8

    A = matriz_aleatoria(m, n)  # Juan: generamos la matriz A de dimension m por n

    B = matriz_aleatoria(m, n)  # Juan: generamos la matriz B de la misma dimension

    R = A + B  # Juan: realizamos la suma elemento a elemento

    print("operacion seleccionada suma")  # Juan: confirmamos la operacion seleccionada

    print("dimensiones de A y B:", A.shape)  # Juan: mostramos las dimensiones de las matrices

    print("A=\n", A)  # Juan: mostramos A

    print("B=\n", B)  # Juan: mostramos B

    print("resultado R=A+B=\n", R)  # Juan: mostramos el resultado de la suma

elif op == 2:  # Juan: si el usuario eligio multiplicacion

    m = rng.integers(2, 9)  # Juan: filas de A entre 2 y 8

    k = rng.integers(2, 9)  # Juan: columnas de A y filas de B entre 2 y 8

    n = rng.integers(2, 9)  # Juan: columnas de B entre 2 y 8

    A = matriz_aleatoria(m, k)  # Juan: generamos la matriz A de dimension m por k

    B = matriz_aleatoria(k, n)  # Juan: generamos la matriz B de dimension k por n

    R = A @ B  # Juan: multiplicamos usando el operador arroba

    print("operacion seleccionada multiplicacion")  # Juan: confirmamos la operacion seleccionada

    print("dimensiones de A:", A.shape, "dimensiones de B:", B.shape)  # Juan: mostramos las dimensiones de A y B

    print("A=\n", A)  # Juan: mostramos A

    print("B=\n", B)  # Juan: mostramos B

    print("resultado R=A@B=\n", R)  # Juan: mostramos el resultado de la multiplicacion

else:  # Juan: si la opcion no es valida

    print("opcion no valida ejecuta de nuevo el bloque y elige 1 o 2")  # Juan: mensaje de opcion invalida


elige una operacion matricial
1 suma
2 multiplicacion
escribe 1 o 2 y presiona enter: 1
operacion seleccionada suma
dimensiones de A y B: (2, 6)
A=
 [[-5  7  3  5  8 -7]
 [-6 -8 -3 -6  7 -2]]
B=
 [[ 2  8  3  6  3  5]
 [-8 -7 -1  6 -6 -7]]
resultado R=A+B=
 [[ -3  15   6  11  11  -2]
 [-14 -15  -4   0   1  -9]]
